# Generated by Django 5.0.2 on 2024-02-14 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlikespost',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userlikespost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='post_userlikespost_unique_user_post'),
        ),
    ]
