# Generated by Django 5.0.2 on 2024-02-17 08:00

import base.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.upload.upload_to_func
            ),
        ),
    ]
