# Generated by Django 5.0.2 on 2024-02-17 08:41

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=post.models.upload_to_func
            ),
        ),
    ]
