# Generated by Django 5.0.2 on 2024-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                default="21.89975",
                max_digits=9,
                verbose_name="latitude",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                default="168.38367",
                max_digits=9,
                verbose_name="longitude",
            ),
        ),
    ]
