# Generated by Django 5.0.2 on 2024-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="latitude"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, null=True, verbose_name="longitude"
            ),
        ),
    ]
