# Generated by Django 5.0.2 on 2024-02-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_latitude_post_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="latitude",
            field=models.FloatField(default=21.89975, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="post",
            name="longitude",
            field=models.FloatField(default=168.38367, verbose_name="longitude"),
        ),
    ]
