# Generated by Django 5.0.2 on 2024-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_latitude_post_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="challenge_count",
            field=models.IntegerField(default=0),
        ),
    ]
