# Generated by Django 5.0.2 on 2024-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_post_challenge_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="secret_text",
            field=models.TextField(blank=True),
        ),
    ]
