# Generated by Django 5.0.2 on 2024-02-17 10:52

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_profile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image_url",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.upload_to_func
            ),
        ),
    ]
