# Generated by Django 5.0.2 on 2024-02-18 00:03

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_profile_image_url_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=user.models.upload_to_func_timetable,
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=user.models.upload_to_func_timetable_result,
                    ),
                ),
            ],
        ),
    ]
