name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: prod

    env:
      IMAGE_TAG: ${{ github.run_number }}
      ECR_REPOSITORY: seeya/seeya-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR to be deployed for K8S
        id: build-image-k8s
        uses: docker/build-push-action@v4
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          build-args: |
            SEEYA_ENV=prod
            SEEYA_SECRET_KEY='${{ secrets.SEEYA_SECRET_KEY }}'
            SEEYA_DB_NAME=${{ secrets.SEEYA_DB_NAME}}
            SEEYA_DB_USER=${{ secrets.SEEYA_DB_USER }}
            SEEYA_DB_PASSWORD=${{ secrets.SEEYA_DB_PASSWORD }}
            SEEYA_DB_HOST=${{ secrets.SEEYA_DB_HOST }}
            SEEYA_DB_PORT=${{ secrets.SEEYA_DB_PORT }}