name: Test pre-commit passed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install poetry
        run: pip install poetry

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry env use 3.11
          poetry install --no-root

      - name: Run pre-commit on changed files
        run: |
          git fetch origin ${{ github.base_ref || 'main' }}
          pre-commit run --from-ref origin/${{ github.base_ref || 'main' }} --to-ref HEAD
