name: Test pre-commit passed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry

      - name: Install poetry
        uses: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on changed files
        run: pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref ${{ github.sha }}
